# Generated by Django 3.0 on 2020-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0004_auto_20200309_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='codigo_postal',
            field=models.PositiveIntegerField(verbose_name='C.P.'),
        ),
    ]
