# Generated by Django 3.0 on 2020-04-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0032_auto_20200330_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_ilimitado', models.BooleanField(default=False, verbose_name='Km Ilimitados')),
                ('h_contrato', models.TimeField(auto_now=True, verbose_name='Hora')),
                ('f_contrato', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('cantidad_c1', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad C1')),
                ('cantidad_c2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad C2')),
                ('cantidad_c3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad C3')),
                ('cantidad_c4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad C4')),
                ('precio_c1', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio C1')),
                ('precio_c2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio C2')),
                ('precio_c3', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio C3')),
                ('precio_c4', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio C4')),
                ('total_c1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total C1')),
                ('total_c2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total C2')),
                ('total_c3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total C3')),
                ('total_c4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total C4')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Contrato')),
                ('fianza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fianza')),
                ('franquicia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Franquicia')),
                ('pago_tarjeta', models.BooleanField(default=False, verbose_name='Pago Tarjeta')),
                ('fianza_tarjeta', models.BooleanField(default=False, verbose_name='Fianza Tarjeta')),
                ('entregado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='entregado')),
                ('reservado', models.BooleanField(default=False, verbose_name='reservado')),
                ('oficina', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oficina')),
                ('ciudad_recogida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad recogida')),
                ('ciudad_devolucion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad devoluvion')),
                ('h_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('f_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('h_fin', models.TimeField(blank=True, null=True, verbose_name='Hora finalización')),
                ('f_fin', models.DateField(blank=True, null=True, verbose_name='Fecha finalización')),
                ('km_libres', models.PositiveIntegerField(default=0, verbose_name='KM libres')),
                ('cliente', models.CharField(max_length=110, verbose_name='Cliente')),
                ('id_cliente', models.PositiveIntegerField(default=0, verbose_name='Id Cliente')),
                ('c_apellido', models.CharField(blank=True, max_length=110, null=True, verbose_name='Apellidos')),
                ('c_nombre', models.CharField(blank=True, max_length=110, null=True, verbose_name='Nombre')),
                ('c_direccion', models.CharField(blank=True, max_length=210, null=True, verbose_name='Dirección')),
                ('c_poblacion', models.CharField(blank=True, max_length=110, null=True, verbose_name='Población')),
                ('c_provincia', models.CharField(blank=True, max_length=110, null=True, verbose_name='Provincia')),
                ('c_cp', models.CharField(blank=True, max_length=10, null=True, verbose_name='C.P.')),
                ('c_pais', models.CharField(blank=True, max_length=110, null=True, verbose_name='País')),
                ('c_telefono', models.CharField(blank=True, max_length=110, null=True, verbose_name='Movil')),
                ('c_movil', models.CharField(blank=True, max_length=110, null=True, verbose_name='Teléfono')),
                ('marca', models.CharField(default='', max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(default='', max_length=30, verbose_name='Modelo')),
                ('t_combustible', models.CharField(default='', max_length=30, verbose_name='Tipo Combustible')),
                ('color', models.CharField(default='', max_length=20, verbose_name='Color')),
                ('id_vehiculo', models.PositiveIntegerField(verbose_name='Id Vehiculo')),
                ('vehiculo', models.CharField(max_length=210, verbose_name='Vehículo')),
                ('km_extra', models.CharField(blank=True, max_length=20, null=True, verbose_name='Km Extra')),
                ('concepto1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pConcepto_1', to='contrato.ConceptoAlquiler', verbose_name='Concepto 1')),
                ('concepto2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pConcepto_2', to='contrato.ConceptoAlquiler', verbose_name='Concepto 2')),
                ('concepto3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pConcepto_3', to='contrato.ConceptoAlquiler', verbose_name='Concepto 3')),
                ('concepto4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pConcepto_4', to='contrato.ConceptoAlquiler', verbose_name='Concepto 4')),
            ],
        ),
    ]
