# Generated by Django 3.0 on 2020-04-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='empleado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Empleado'),
        ),
    ]
