# Generated by Django 3.0 on 2020-01-30 08:20

import cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='document1',
            field=models.FileField(blank=True, null=True, upload_to=cliente.models.custom_upload_to1, verbose_name='Documentación 1'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to=cliente.models.custom_upload_to2, verbose_name='Documentación 2'),
        ),
    ]
