# Generated by Django 3.0 on 2020-01-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200130_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='C.P.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('N.I.F.', 'N.I.F.'), ('Pasaporte', 'Pasaporte'), ('C.I.F.', 'C.I.F.')], max_length=20, verbose_name='Tipo de documentación'),
        ),
    ]
