# Generated by Django 3.0 on 2020-01-29 17:36

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200124_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_user',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to, verbose_name='Avatar'),
        ),
    ]
