# Generated by Django 3.0 on 2020-02-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_agencia_codigo'),
        ('registration', '0007_auto_20200129_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agencia.Agencia'),
        ),
    ]
