# Generated by Django 3.0 on 2020-02-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_profile_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ciudad',
            new_name='oficina',
        ),
    ]
