# Generated by Django 3.0 on 2020-02-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200204_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='f_carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Franquicia Carga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='f_turismo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Franquicia Turismo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fianza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fianza'),
        ),
    ]
