# Generated by Django 3.0 on 2020-02-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20200217_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trato',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Atendido por'),
        ),
    ]
