# Generated by Django 3.0 on 2020-03-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_profile_trato'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='km_extra_carga',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Km extra carga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='km_extra_turismo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Km extra turismo'),
        ),
    ]
