# Generated by Django 3.0 on 2020-04-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0005_auto_20200311_1805'),
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencia.Agencia'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('FA', 'FA'), ('FB', 'FB'), ('FC', 'FC'), ('FD', 'FD'), ('FE', 'FE'), ('FF', 'FD')], max_length=2, verbose_name='Grupo'),
        ),
    ]
