# Generated by Django 3.0 on 2020-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_auto_20200430_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='k1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='1 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='10 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='11 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='12 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k13',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='13 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k14',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='14 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k15',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='15 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k16',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='16 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k17',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='17 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k18',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='18 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k19',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='19 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='2 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='20 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k21',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='21 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k22',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='22 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k23',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='23 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k24',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='24 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k25',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='25 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k26',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='26 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k27',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='27 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k28',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='28 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k29',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='29 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='3 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k30',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='30 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k31',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='31 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='4 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='5 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='6 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='7 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='8 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='k9',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='9 d/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='1 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='10 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='11 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='12 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka13',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='13 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka14',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='14 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka15',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='15 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka16',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='16 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka17',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='17 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka18',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='18 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka19',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='19 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='2 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='20 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka21',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='21 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka22',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='22 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka23',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='23 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka24',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='24 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka25',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='25 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka26',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='26 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka27',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='27 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka28',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='28 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka29',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='29 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='3 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka30',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='30 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka31',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='31 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='4 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='5 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='6 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='7 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='8 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ka9',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='9 d_A/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='1 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='10 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='11 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='12 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km13',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='13 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km14',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='14 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km15',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='15 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km16',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='16 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km17',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='17 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km18',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='18 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km19',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='19 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='2 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='20 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km21',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='21 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km22',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='22 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km23',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='23 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km24',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='24 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km25',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='25 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km26',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='26 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km27',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='27 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km28',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='28 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km29',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='29 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='3 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km30',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='30 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km31',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='31 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='4 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='5 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='6 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='7 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='8 d_M/km'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='km9',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='9 d_M/km'),
        ),
    ]
