# Generated by Django 3.0 on 2020-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0003_auto_20200518_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='ciudad',
            field=models.CharField(max_length=20, verbose_name='Ciudad'),
        ),
    ]
