# Generated by Django 3.0 on 2020-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0005_grupo_ciudad2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='ciudad2',
            field=models.CharField(max_length=20, verbose_name='Ciudad2'),
        ),
    ]
