# Generated by Django 3.0 on 2020-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_auto_20200121_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('Rojo', 'Rojo'), ('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Gris Claro', 'Gris Claro'), ('Gris Oscuro', 'Gris Oscuro'), ('Azul', 'Azul'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
