# Generated by Django 3.0 on 2020-04-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0007_auto_20200210_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('FA', 'FA'), ('FB', 'FB'), ('FC', 'FC'), ('FD', 'FD'), ('FE', 'FE'), ('FF', 'FD')], max_length=2, null=True),
        ),
    ]
