# Generated by Django 3.0 on 2020-02-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0005_auto_20200131_1127'),
        ('vehiculo', '0006_auto_20200121_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoAlquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50, verbose_name='Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_contrato', models.TimeField(auto_now=True, verbose_name='Hora')),
                ('f_contrato', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('combustible', models.CharField(choices=[('F', 'F'), ('7/8', '7/8'), ('3/4', '3/4'), ('5/8', '5/8'), ('1/2', '1/2'), ('3/8', '3/8'), ('1/4', '1/4'), ('1/8', '1/8'), ('E', 'E')], max_length=4)),
                ('oficina', models.CharField(max_length=15, verbose_name='Oficina')),
                ('c_madrid', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contrato Madrid')),
                ('c_salamanca', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contrato Madrid')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cliente', to='cliente.Cliente', verbose_name='Cliente')),
                ('concepto1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Concepto_1', to='contrato.ConceptoAlquiler', verbose_name='Concepto 1')),
                ('concepto2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto_2', to='contrato.ConceptoAlquiler', verbose_name='Concepto 2')),
                ('concepto3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto_3', to='contrato.ConceptoAlquiler', verbose_name='Concepto 3')),
                ('concepto4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto_4', to='contrato.ConceptoAlquiler', verbose_name='Concepto 4')),
                ('concepto5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto_5', to='contrato.ConceptoAlquiler', verbose_name='Concepto 5')),
                ('concepto6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto_6', to='contrato.ConceptoAlquiler', verbose_name='Concepto 6')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Conductor', to='cliente.Cliente', verbose_name='Conductor')),
                ('conductor_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Coductor_Adicional', to='cliente.Cliente', verbose_name='Coductor Adicional')),
                ('vehículo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculo.Vehiculo', verbose_name='Vehículo')),
            ],
        ),
    ]
