# Generated by Django 3.0 on 2020-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='oficina',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Oficina'),
        ),
    ]
