# Generated by Django 3.0 on 2020-02-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_auto_20200204_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='b_madrid',
            field=models.BooleanField(default=False, verbose_name='Contabilizar Madrid'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_madrid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Contrato Madrid'),
        ),
    ]
