# Generated by Django 3.0 on 2020-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_auto_20200204_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='b_las_palmas',
            field=models.BooleanField(default=False, verbose_name='Contabilizar Las Palmas'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='b_mallorca',
            field=models.BooleanField(default=False, verbose_name='Contabilizar Mallorca'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='b_salamanca',
            field=models.BooleanField(default=False, verbose_name='Contabilizar Salamanca'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='b_valladolid',
            field=models.BooleanField(default=False, verbose_name='Contabilizar Valladolid'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='b_zamora',
            field=models.BooleanField(default=False, verbose_name='Contabilizar Zamora'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_las_palmas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Contrato Las Palmas'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_mallorca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Contrato Mallorca'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_valladolid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Contrato Valladolid'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_zamora',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Contrato Zamora'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_salamanca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Contrato Salamanca'),
        ),
    ]
