# Generated by Django 3.0 on 2020-02-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_auto_20200204_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='c_general',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Contrato Zamora'),
        ),
    ]
