# Generated by Django 3.0 on 2020-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0005_contrato_c_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cantidad_c1',
            field=models.IntegerField(default=0, verbose_name='Cantidad C1'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cantidad_c2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad C2'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cantidad_c3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad C3'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cantidad_c4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad C4'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cantidad_c5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad C5'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cantidad_c6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad C6'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fianza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fianza'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='franquicia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Franquicia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ianza_tarjeta',
            field=models.BooleanField(default=False, verbose_name='Fianza Tarjeta'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pago_tarjeta',
            field=models.BooleanField(default=False, verbose_name='Pago Tarjeta'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='total_c1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Total C1'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='total_c2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total C2'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='total_c3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total C3'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='total_c4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total C4'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='total_c5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total C5'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='total_c6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total C6'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_general',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Contrato General'),
        ),
    ]
