# Generated by Django 3.0 on 2020-02-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0006_auto_20200205_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ciudad_devolucion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad devoluvion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ciudad_recogida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad recogida'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='f_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha finalización'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='f_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='h_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora finalización'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='h_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora inicio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='km_fin',
            field=models.PositiveIntegerField(default=0, verbose_name='KM libres'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='km_inicio',
            field=models.PositiveIntegerField(default=0, verbose_name='KM libres'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='km_libres',
            field=models.PositiveIntegerField(default=0, verbose_name='KM libres'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_general',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº General'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_las_palmas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Las Palmas'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_madrid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Madrid'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_mallorca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº  Mallorca'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_salamanca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Salamanca'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_valladolid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Valladolid'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='c_zamora',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Zamora'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cantidad_c1',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Cantidad C1'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cantidad_c2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cantidad C2'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cantidad_c3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cantidad C3'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cantidad_c4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cantidad C4'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cantidad_c5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cantidad C5'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cantidad_c6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cantidad C6'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='oficina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Oficina'),
        ),
    ]
