# Generated by Django 3.0 on 2020-02-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0007_auto_20200205_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='vehículo',
            new_name='vehiculo',
        ),
    ]
