# Generated by Django 3.0 on 2020-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0008_auto_20200205_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='alquilado',
            field=models.BooleanField(default=True, verbose_name='Alquilado'),
        ),
    ]
