# Generated by Django 3.0 on 2020-02-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0009_contrato_alquilado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cortesia',
            field=models.BooleanField(default=False, verbose_name='Cortesia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sustitución',
            field=models.BooleanField(default=False, verbose_name='Sustitución'),
        ),
    ]
