# Generated by Django 3.0 on 2020-02-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0010_auto_20200205_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='sustitución',
            new_name='sustitucion',
        ),
    ]
