# Generated by Django 3.0 on 2020-02-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0011_auto_20200205_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='ianza_tarjeta',
            new_name='fianza_tarjeta',
        ),
    ]
