# Generated by Django 3.0 on 2020-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0012_auto_20200206_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='color',
            field=models.CharField(default='', max_length=20, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='marca',
            field=models.CharField(default='', max_length=30, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modelo',
            field=models.CharField(default='', max_length=30, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='t_combustible',
            field=models.CharField(default='', max_length=30, verbose_name='Tipo Combustible'),
        ),
    ]
