# Generated by Django 3.0 on 2020-02-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0013_auto_20200210_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='id_cliente',
            field=models.PositiveIntegerField(default=0, verbose_name='Id Cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_conductor',
            field=models.PositiveIntegerField(default=0, verbose_name='Id Conductor'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_conductor_ad',
            field=models.PositiveIntegerField(default=0, verbose_name='Id Conductor Adicional'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_vehiculo',
            field=models.PositiveIntegerField(default=0, verbose_name='Id Vehiculo'),
        ),
    ]
