# Generated by Django 3.0 on 2020-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0014_auto_20200210_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='apellido',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='C.P.'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='direccion',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='f_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha caducidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='f_exp',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha expedicion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='f_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='l_exp',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Lugar expedición'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='licencia',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Nº de licéncia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='movil',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='nombre',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pais',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='poblacion',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Población'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='provincia',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='telefono',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Movil'),
        ),
    ]
