# Generated by Django 3.0 on 2020-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0015_auto_20200210_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='a_apellido',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='C.P.'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_direccion',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_f_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha caducidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_f_exp',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha expedicion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_f_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_l_exp',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Lugar expedición'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_licencia',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Nº de licéncia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_movil',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_nombre',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_pais',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_poblacion',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Población'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_provincia',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='a_telefono',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Movil'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_apellido',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='C.P.'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_direccion',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_movil',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_nombre',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_pais',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_poblacion',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Población'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_provincia',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='c_telefono',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Movil'),
        ),
    ]
