# Generated by Django 3.0 on 2020-02-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0016_auto_20200211_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='adicional',
            field=models.BooleanField(default=False, verbose_name='Sustitución'),
        ),
    ]
