# Generated by Django 3.0 on 2020-02-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0018_auto_20200214_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='combustible',
            field=models.CharField(choices=[('F', 'F'), ('7/8', '7/8'), ('3/4', '3/4'), ('5/8', '5/8'), ('1/2', '1/2'), ('3/8', '3/8'), ('1/4', '1/4'), ('1/8', '1/8'), ('E', 'E')], default=1, max_length=4),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='precio_c1',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio C1'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='precio_c2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio C2'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='precio_c3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio C3'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='precio_c4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio C4'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='precio_c5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio C5'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='precio_c6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio C6'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='total_c1',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total C1'),
        ),
    ]
