# Generated by Django 3.0 on 2020-02-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0020_auto_20200217_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.CharField(max_length=110, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='conductor',
            field=models.CharField(max_length=110, verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='conductor_a',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Coductor Adicional'),
        ),
    ]
