# Generated by Django 3.0 on 2020-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0022_auto_20200217_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='km_fin',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='KM fin'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='km_inicio',
            field=models.PositiveIntegerField(default=0, verbose_name='KM inicio'),
        ),
    ]
