# Generated by Django 3.0 on 2020-02-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0023_auto_20200218_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='id_conductor_ad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id Conductor Adicional'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id_vehiculo',
            field=models.PositiveIntegerField(verbose_name='Id Vehiculo'),
        ),
    ]
