# Generated by Django 3.0 on 2020-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0024_auto_20200218_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='adicional',
            field=models.BooleanField(default=False, verbose_name='Adicional'),
        ),
    ]
