# Generated by Django 3.0 on 2020-02-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0025_auto_20200219_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='observacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones'),
        ),
    ]
