# Generated by Django 3.0 on 2020-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0027_contrato_km_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='km_extra',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Km Extra'),
        ),
    ]
