# Generated by Django 3.0 on 2020-03-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0028_auto_20200303_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='km_ilimitado',
            field=models.BooleanField(default=False, verbose_name='Km Ilimitados'),
        ),
    ]
