# Generated by Django 3.0 on 2020-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0029_contrato_km_ilimitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='observacion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Observaciones'),
        ),
    ]
