# Generated by Django 3.0 on 2020-03-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0030_auto_20200304_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fianza_deposito',
            field=models.BooleanField(default=False, verbose_name='Fianza en depósito'),
        ),
    ]
