# Generated by Django 3.0 on 2020-03-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0031_contrato_fianza_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='observacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones'),
        ),
    ]
